CREATE DATABASE REGISTRO

USE REGISTRO

CREATE TABLE ALUMNO
(
IDENTIFICACION VARCHAR(10) PRIMARY KEY,
NOMBRE VARCHAR (100),
APELLIDO VARCHAR (100),
EDAD VARCHAR (3)

)

INSERT INTO ALUMNO VALUES ('123','PEDRO JOSE','VASQUEZ','25')
USE REGISTRO
SELECT*FROM ALUMNO